const products =[
      {
    id: 1,
    name: "Pharma Dry syrup Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Durable and hygienic bottles specially designed for safe storage of dry syrups. Ensures moisture protection, tamper-resistance, and accurate pouring to maintain medicine stability and shelf life.",
        images : [
    { src: "/product1.png", alt: "Syrup bottle and box mockup" },
    { src: "/product3.png", alt: "Brown glass bottle" },
    { src: "/product6.png", alt: "White medicine bottle" },
    { src: "/product4.png", alt: "Label close-up" },
    { src: "/product5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 2,
    name: "Measuring Spoons",
    rating: 4.8,
    reviews: 49,
    description: "Precision-engineered spoons designed for consistent dosing of powders and liquids. Lightweight, reusable, and available in multiple sizes to suit varied medical applications.",
        images : [
    { src: "/spoon.png", alt: "Syrup bottle and box mockup" },
    { src: "/spoon2.png", alt: "Brown glass bottle" },
    { src: "/spoon3.png", alt: "White medicine bottle" },
    { src: "/spoon4.png", alt: "Label close-up" },
    { src: "/spoon5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 3,
    name: "Lotion Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Easy-to-use bottles with pumps or flip tops for smooth application of lotions and moisturizers. Durable material ensures long-lasting freshness and brand appeal.",
        images : [
    { src: "/lotionbottle.png", alt: "Syrup bottle and box mockup" },
    { src: "/lotionbottle2.png", alt: "Brown glass bottle" },
    { src: "/lotionbottle3.png", alt: "White medicine bottle" },
    { src: "/lotionbottle4.png", alt: "Label close-up" },
    { src: "/lotionbottle5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 4,
    name: "Hand wash Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Practical, stylish bottles with pump dispensers for liquid hand wash. Designed for convenience, hygiene, and smooth flow with every press.",
        images : [
    { src: "/handwash.png", alt: "Syrup bottle and box mockup" },
    { src: "/handwash2.png", alt: "Brown glass bottle" },
    { src: "/handwash3.png", alt: "White medicine bottle" },
    { src: "/handwash4.png", alt: "Label close-up" },
    { src: "/handwash5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },

     {
    id: 5,
    name: "Eye-Ear Dropper Bottle",
    rating: 4.8,
    reviews: 49,
    description: "Precision plastic dropper bottles for eye and ear care, ensuring accurate dosing and lasting freshness with hygienic, leak-proof design.",
        images : [
    { src: "/dropper.png", alt: "Syrup bottle and box mockup" },
    { src: "/dropper2.png", alt: "Brown glass bottle" },
    { src: "/dropper3.png", alt: "White medicine bottle" },
    { src: "/dropper4.png", alt: "Label close-up" },
    { src: "/dropper5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 6,
    name: "Flip-off Seals",
    rating: 4.8,
    reviews: 49,
    description: "Heavy-duty lock fittings ensuring airtight and insulated sealing of cold room panels. Provides maximum energy efficiency, durability, and long-term reliability in cold storage.",
        images : [
    { src: "/flipoff.png", alt: "Syrup bottle and box mockup" },
    { src: "/flipoff2.png", alt: "Brown glass bottle" },
    { src: "/flipoff3.png", alt: "White medicine bottle" },
    { src: "/flipoff4.png", alt: "Label close-up" },
    { src: "/flipoff5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 7,
    name: "RoPP Caps for Pharma PET Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Tamper-proof, reliable RoPP (Roll-on Pilfer Proof) caps that guarantee product safety and consumer confidence. Provides leak-free closure with strong grip and hygienic sealing.",
        images : [
    { src: "/caps.png", alt: "Syrup bottle and box mockup" },
    { src: "/caps1.png", alt: "Brown glass bottle" },
    { src: "/caps2.png", alt: "White medicine bottle" },
    { src: "/cap3.png", alt: "Label close-up" },
    { src: "/caps4.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 8,
    name: "Toilet cleaner bottles",
    rating: 4.8,
    reviews: 49,
    description: "Specially designed bottles with angled necks for effective and targeted cleaning. Built strong to withstand harsh chemicals and ensure safe handling.",
        images : [
    { src: "/toiletCleaner.png", alt: "Syrup bottle and box mockup" },
    { src: "/toiletCleaner2.png", alt: "Brown glass bottle" },
    { src: "/toiletCleaner3.png", alt: "White medicine bottle" },
    { src: "/toiletCleaner4.png", alt: "Label close-up" },
    { src: "/toiletCleaner5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 9,
    name: "Cream Jars",
    rating: 4.8,
    reviews: 49,
    description: "Compact, stylish jars suitable for creams, ointments, balms, and gels. Ensures airtight protection, extended shelf life, and premium appeal for skincare and pharma products.",
        images : [
    { src: "/jars1.png", alt: "Syrup bottle and box mockup" },
    { src: "/jars2.png", alt: "Brown glass bottle" },
    { src: "/jars3.png", alt: "White medicine bottle" },
    { src: "/jars4.png", alt: "Label close-up" },
    { src: "/jars5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },

    {
    id: 10,
    name: "Shampoo Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Attractive and functional shampoo bottles designed with durability and consumer convenience in mind. Provides smooth dispensing and leak-proof design for personal care brands.",
        images : [
    { src: "/shampoobottle.png", alt: "Syrup bottle and box mockup" },
    { src: "/shampoobottle2.png", alt: "Brown glass bottle" },
    { src: "/shampoobottle3.png", alt: "White medicine bottle" },
    { src: "/shampoobottle4.png", alt: "Label close-up" },
    { src: "/shampoobottle5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },

     {
    id: 11,
    name: "Oil Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Versatile bottles ideal for edible, cosmetic, and therapeutic oils. Engineered for strength, leak resistance, and hygienic preservation of product quality.",
        images : [
    { src: "/oilbottle.png", alt: "Syrup bottle and box mockup" },
    { src: "/oilbottle2.png", alt: "Brown glass bottle" },
    { src: "/oilbottle3.png", alt: "White medicine bottle" },
    { src: "/oilbottle4.png", alt: "Label close-up" },
    { src: "/oilbottle5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
  {
    id: 12,
    name: "Floor cleaner bottles",
    rating: 4.8,
    reviews: 49,
    description: "Ergonomic bottles tailored for strong cleaning solutions. Leak-proof design and comfortable grip make them ideal for safe storage and everyday use.",
        images : [
    { src: "/floorCleaner.png", alt: "Syrup bottle and box mockup" },
    { src: "/floorCleaner2.png", alt: "Brown glass bottle" },
    { src: "/floorCleaner3.png", alt: "White medicine bottle" },
    { src: "/floorCleaner4.png", alt: "Label close-up" },
    { src: "/floorCleaner5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 13,
    name: "Pharmaceutical rubber Dropper assembly",
    rating: 4.8,
    reviews: 49,
    description: "Precision plastic dropper bottles for eye and ear care, ensuring accurate dosing and lasting freshness with a hygienic, leak-proof design. Perfect for sensitive medical use.",
        images : [
    { src: "/PharmaceuticalRubber.png", alt: "Syrup bottle and box mockup" },
    { src: "/PharmaceuticalRubber2.png", alt: "Brown glass bottle" },
    { src: "/PharmaceuticalRubber3.png", alt: "White medicine bottle" },
    { src: "/PharmaceuticalRubber4.png", alt: "Label close-up" },
    { src: "/PharmaceuticalRubber5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 14,
    name: "Stopper CAM Lock fittings for Cold rooms PUF Panels",
    rating: 4.8,
    reviews: 49,
    description: "Heavy-duty lock fittings ensuring airtight and insulated sealing of cold room panels. Provides maximum energy efficiency, durability, and long-term reliability in cold storage.",
        images : [
    { src: "/stopperCAM.png", alt: "Syrup bottle and box mockup" },
    { src: "/stopperCAM2.png", alt: "Brown glass bottle" },
    { src: "/stopperCAM3.png", alt: "White medicine bottle" },
    { src: "/stopperCAM4.png", alt: "Label close-up" },
    { src: "/stopperCAM5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
     {
    id: 15,
    name: "Churan Bottle Set",
    rating: 4.8,
    reviews: 49,
    description: "High-quality PET bottles ensuring safe packaging of pharmaceutical syrups, liquids, and suspensions. Known for clarity, durability, and leak-proof sealing for ultimate protection.",
        images : [
    { src: "/churanbottle.png", alt: "Syrup bottle and box mockup" },
    { src: "/churanbottle2.png", alt: "Brown glass bottle" },
    { src: "/churanbottle3.png", alt: "White medicine bottle" },
    { src: "/churanbottl4.png", alt: "Label close-up" },
    { src: "/churanbottl5.png", alt: "Packaging box" },
  ],
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
   },
]

export default products