const products =[
      {
  //   id: 1,
  //   name: "Pharma Dry syrup Bottles",
  //   rating: 4.8,
  //   reviews: 49,
  //   description: "Durable and hygienic bottles specially designed for safe storage of dry syrups. Ensures moisture protection, tamper-resistance, and accurate pouring to maintain medicine stability and shelf life.",
  //       images : [
  //   { src: "/product1.png", alt: "Syrup bottle and box mockup" },
  //   { src: "/product3.png", alt: "Brown glass bottle" },
  //   { src: "/product6.png", alt: "White medicine bottle" },
  //   { src: "/product4.png", alt: "Label close-up" },
  //   { src: "/product5.png", alt: "Packaging box" },
  // ],
  //   specs: [
  //     { label: "Color", value: "White" },
  //     { label: "Usage", value: "Laboratory" },
  //     { label: "Size", value: "Standard" },
  //     { label: "Product Type", value: "Adaptors Bottles" },
  //     { label: "Material", value: "PTFE" },
  //     { label: "Application", value: "Industrial" },
  //     { label: "Supply Ability", value: "1000 Per Day" },
  //     { label: "Delivery Time", value: "4-5 Days" },
  //   ],
  //   sizes: [
  //     "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
  //     "50 ml", "60 ml", "70 ml", "80 ml",
  //     "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
  //     "55 ml", "65 ml", "75 ml", "85 ml",
  //   ],
  //  },
  //    {
  //   id: 2,
  //   name: "Measuring Spoons",
  //   rating: 4.8,
  //   reviews: 49,
  //   description: "Precision-engineered spoons designed for consistent dosing of powders and liquids. Lightweight, reusable, and available in multiple sizes to suit varied medical applications.",
  //       images : [
  //   { src: "/spoon.png", alt: "Syrup bottle and box mockup" },
  //   { src: "/spoon2.png", alt: "Brown glass bottle" },
  //   { src: "/spoon3.png", alt: "White medicine bottle" },
  //   { src: "/spoon4.png", alt: "Label close-up" },
  //   { src: "/spoon5.png", alt: "Packaging box" },
  // ],
  //   specs: [
  //     { label: "Color", value: "White" },
  //     { label: "Usage", value: "Laboratory" },
  //     { label: "Size", value: "Standard" },
  //     { label: "Product Type", value: "Adaptors Bottles" },
  //     { label: "Material", value: "PTFE" },
  //     { label: "Application", value: "Industrial" },
  //     { label: "Supply Ability", value: "1000 Per Day" },
  //     { label: "Delivery Time", value: "4-5 Days" },
  //   ],
  //   sizes: [
  //     "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
  //     "50 ml", "60 ml", "70 ml", "80 ml",
  //     "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
  //     "55 ml", "65 ml", "75 ml", "85 ml",
  //   ],

  id: 1,
    name: "Pharma Dry syrup Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Durable and hygienic bottles specially designed for safe storage of dry syrups. Ensures moisture protection, tamper-resistance, and accurate pouring to maintain medicine stability and shelf life.",
    
    // Default images
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Syrup bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White medicine bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Packaging box" },
    ],
    
    // Size-specific images in increasing order
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i5.jpg", alt: "5ml Syrup bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White medicine bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Medicine bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Syrup bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White medicine bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Medicine bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Syrup bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White medicine bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Medicine bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Syrup bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White medicine bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Medicine bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Syrup bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White medicine bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Medicine bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Syrup bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White medicine bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Medicine bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Syrup bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White medicine bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Medicine bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Syrup bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White medicine bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Medicine bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Syrup bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White medicine bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Medicine bottle" },
      ],
    },
    
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Adaptors Bottles" },
      { label: "Material", value: "PTFE" },
      { label: "Application", value: "Industrial" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "8 ml", "10 ml", "15 ml", "20 ml",
      "25 ml", "30 ml", "35 ml", "40 ml", "45 ml",
      "50 ml", "55 ml", "60 ml", "65 ml", "70 ml",
      "75 ml", "80 ml", "85 ml"
    ],
   },
   // Add this product after ID 1 and before ID 3 in your products array
{
  id: 2,
  name: "Measuring Spoons",
  rating: 4.8,
  reviews: 49,
  description: "High-quality Measuring Spoons ensuring safe packaging of pharmaceutical syrups, liquids, and suspensions. Known for clarity, durability, and leak-proof sealing for ultimate protection.",
  
  images: [
    { src: "/medicine_img/i1.jpg", alt: "PET bottle and box mockup" },
    { src: "/medicine_img/i2.jpg", alt: "Brown glass PET bottle" },
    { src: "/medicine_img/i3.jpg", alt: "White PET bottle" },
    { src: "/medicine_img/i4.jpg", alt: "PET label close-up" },
    { src: "/medicine_img/i5.jpg", alt: "PET packaging box" },
  ],
  
  sizeImages: {
    "5 ml": [
      { src: "/medicine_img/i1.jpg", alt: "5ml PET bottle" },
      { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass PET bottle" },
      { src: "/medicine_img/i3.jpg", alt: "5ml White PET bottle" },
    ],
    "8 ml": [
      { src: "/medicine_img/i4.jpg", alt: "8ml PET label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "8ml PET packaging box" },
      { src: "/medicine_img/i6.jpg", alt: "8ml PET bottle" },
    ],
    "10 ml": [
      { src: "/medicine_img/i7.jpg", alt: "10ml PET bottle" },
      { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass PET bottle" },
      { src: "/medicine_img/i9.jpg", alt: "10ml White PET bottle" },
    ],
    "15 ml": [
      { src: "/medicine_img/i10.jpg", alt: "15ml PET label close-up" },
      { src: "/medicine_img/i11.jpg", alt: "15ml PET packaging box" },
      { src: "/medicine_img/i12.jpg", alt: "15ml PET bottle" },
    ],
    "20 ml": [
      { src: "/medicine_img/i13.jpg", alt: "20ml PET bottle" },
      { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass PET bottle" },
      { src: "/medicine_img/i15.jpg", alt: "20ml White PET bottle" },
    ],
    "25 ml": [
      { src: "/medicine_img/i16.jpg", alt: "25ml PET label close-up" },
      { src: "/medicine_img/i1.jpg", alt: "25ml PET packaging box" },
      { src: "/medicine_img/i2.jpg", alt: "25ml PET bottle" },
    ],
    "30 ml": [
      { src: "/medicine_img/i3.jpg", alt: "30ml PET bottle" },
      { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass PET bottle" },
      { src: "/medicine_img/i5.jpg", alt: "30ml White PET bottle" },
    ],
    "35 ml": [
      { src: "/medicine_img/i6.jpg", alt: "35ml PET label close-up" },
      { src: "/medicine_img/i7.jpg", alt: "35ml PET packaging box" },
      { src: "/medicine_img/i8.jpg", alt: "35ml PET bottle" },
    ],
    "40 ml": [
      { src: "/medicine_img/i9.jpg", alt: "40ml PET bottle" },
      { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass PET bottle" },
      { src: "/medicine_img/i11.jpg", alt: "40ml White PET bottle" },
    ],
    "45 ml": [
      { src: "/medicine_img/i12.jpg", alt: "45ml PET label close-up" },
      { src: "/medicine_img/i13.jpg", alt: "45ml PET packaging box" },
      { src: "/medicine_img/i14.jpg", alt: "45ml PET bottle" },
    ],
    "50 ml": [
      { src: "/medicine_img/i15.jpg", alt: "50ml PET bottle" },
      { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass PET bottle" },
      { src: "/medicine_img/i1.jpg", alt: "50ml White PET bottle" },
    ],
    "55 ml": [
      { src: "/medicine_img/i2.jpg", alt: "55ml PET label close-up" },
      { src: "/medicine_img/i3.jpg", alt: "55ml PET packaging box" },
      { src: "/medicine_img/i4.jpg", alt: "55ml PET bottle" },
    ],
    "60 ml": [
      { src: "/medicine_img/i5.jpg", alt: "60ml PET bottle" },
      { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass PET bottle" },
      { src: "/medicine_img/i7.jpg", alt: "60ml White PET bottle" },
    ],
    "65 ml": [
      { src: "/medicine_img/i8.jpg", alt: "65ml PET label close-up" },
      { src: "/medicine_img/i9.jpg", alt: "65ml PET packaging box" },
      { src: "/medicine_img/i10.jpg", alt: "65ml PET bottle" },
    ],
    "70 ml": [
      { src: "/medicine_img/i11.jpg", alt: "70ml PET bottle" },
      { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass PET bottle" },
      { src: "/medicine_img/i13.jpg", alt: "70ml White PET bottle" },
    ],
    "75 ml": [
      { src: "/medicine_img/i14.jpg", alt: "75ml PET label close-up" },
      { src: "/medicine_img/i15.jpg", alt: "75ml PET packaging box" },
      { src: "/medicine_img/i16.jpg", alt: "75ml PET bottle" },
    ],
    "80 ml": [
      { src: "/medicine_img/i1.jpg", alt: "80ml PET bottle" },
      { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass PET bottle" },
      { src: "/medicine_img/i3.jpg", alt: "80ml White PET bottle" },
    ],
    "85 ml": [
      { src: "/medicine_img/i4.jpg", alt: "85ml PET label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "85ml PET packaging box" },
      { src: "/medicine_img/i6.jpg", alt: "85ml PET bottle" },
    ],
  },
  
  specs: [
    { label: "Color", value: "Transparent" },
    { label: "Usage", value: "Pharmaceutical" },
    { label: "Size", value: "Standard" },
    { label: "Product Type", value: "PET Bottles" },
    { label: "Material", value: "PET" },
    { label: "Application", value: "Liquid Storage" },
    { label: "Supply Ability", value: "1000 Per Day" },
    { label: "Delivery Time", value: "4-5 Days" },
  ],
  sizes: [
    "5 ml", "8 ml", "10 ml", "15 ml", "20 ml",
    "25 ml", "30 ml", "35 ml", "40 ml", "45 ml",
    "50 ml", "55 ml", "60 ml", "65 ml", "70 ml",
    "75 ml", "80 ml", "85 ml"
  ],
},
     {
    id: 3,
    name: "Lotion Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Easy-to-use bottles with pumps or flip tops for smooth application of lotions and moisturizers. Durable material ensures long-lasting freshness and brand appeal.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Lotion bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass lotion bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White lotion bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Lotion label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Lotion packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i6.jpg", alt: "5ml Lotion bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass lotion bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White lotion bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Lotion label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Lotion packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Lotion bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Lotion bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass lotion bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White lotion bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Lotion label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Lotion packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Lotion bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Lotion bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass lotion bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White lotion bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Lotion label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Lotion packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Lotion bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Lotion bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass lotion bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White lotion bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Lotion label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Lotion packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Lotion bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Lotion bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass lotion bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White lotion bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Lotion label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Lotion packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Lotion bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Lotion bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass lotion bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White lotion bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Lotion label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Lotion packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Lotion bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Lotion bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass lotion bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White lotion bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Lotion label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Lotion packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Lotion bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Lotion bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass lotion bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White lotion bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Lotion label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Lotion packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Lotion bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Lotion bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass lotion bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White lotion bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Lotion label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Lotion packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Lotion bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Lotion Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Personal Care" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 4,
    name: "Hand wash Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Practical, stylish bottles with pump dispensers for liquid hand wash. Designed for convenience, hygiene, and smooth flow with every press.",
    images: [
      { src: "/medicine_img/i9.jpg", alt: "Hand wash bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass hand wash bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White hand wash bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Hand wash label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Hand wash packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i8.jpg", alt: "5ml Hand wash bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White hand wash bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Hand wash label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Hand wash packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Hand wash bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Hand wash bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White hand wash bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Hand wash label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Hand wash packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Hand wash bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Hand wash bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White hand wash bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Hand wash label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Hand wash packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Hand wash bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Hand wash bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White hand wash bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Hand wash label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Hand wash packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Hand wash bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Hand wash bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White hand wash bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Hand wash label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Hand wash packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Hand wash bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Hand wash bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White hand wash bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Hand wash label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Hand wash packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Hand wash bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Hand wash bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White hand wash bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Hand wash label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Hand wash packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Hand wash bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Hand wash bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White hand wash bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Hand wash label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Hand wash packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Hand wash bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Hand wash bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass hand wash bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White hand wash bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Hand wash label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Hand wash packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Hand wash bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Hand Wash Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Personal Care" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 5,
    name: "Eye-Ear Dropper Bottle",
    rating: 4.8,
    reviews: 49,
    description: "Precision plastic dropper bottles for eye and ear care, ensuring accurate dosing and lasting freshness with hygienic, leak-proof design.",
    images: [
      { src: "/medicine_img/i11.jpg", alt: "Dropper bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass dropper bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White dropper bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Dropper label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Dropper packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i12.jpg", alt: "5ml Dropper bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass dropper bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White dropper bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Dropper label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Dropper packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Dropper bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Dropper bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass dropper bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White dropper bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Dropper label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Dropper packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Dropper bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Dropper bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass dropper bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White dropper bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Dropper label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Dropper packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Dropper bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Dropper bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass dropper bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White dropper bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Dropper label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Dropper packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Dropper bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Dropper bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass dropper bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White dropper bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Dropper label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Dropper packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Dropper bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Dropper bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass dropper bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White dropper bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Dropper label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Dropper packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Dropper bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Dropper bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass dropper bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White dropper bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Dropper label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Dropper packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Dropper bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Dropper bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass dropper bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White dropper bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Dropper label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Dropper packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Dropper bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Dropper bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass dropper bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White dropper bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Dropper label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Dropper packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Dropper bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Laboratory" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Dropper Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Medical" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  
  {
    id: 6,
    name: "Flip-off Seals",
    rating: 4.8,
    reviews: 49,
    description: "Tamper-evident seals for pharmaceutical containers ensuring product safety and integrity with easy flip-off mechanism for consumer convenience.",
    images: [
      { src: "/medicine_img/i2.jpg", alt: "Flip-off seals and box mockup" },
      { src: "/medicine_img/i5.jpg", alt: "Brown glass with flip-off seal" },
      { src: "/medicine_img/i3.jpg", alt: "White container with flip-off seal" },
      { src: "/medicine_img/i4.jpg", alt: "Seal label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Seals packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i2.jpg", alt: "5ml Flip-off seal" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass with seal" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White container with seal" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Seal label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Seals packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Flip-off seal" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Flip-off seal" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass with seal" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White container with seal" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Seal label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Seals packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Flip-off seal" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Flip-off seal" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass with seal" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White container with seal" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Seal label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Seals packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Flip-off seal" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Flip-off seal" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass with seal" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White container with seal" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Seal label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Seals packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Flip-off seal" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Flip-off seal" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass with seal" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White container with seal" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Seal label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Seals packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Flip-off seal" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Flip-off seal" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass with seal" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White container with seal" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Seal label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Seals packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Flip-off seal" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Flip-off seal" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass with seal" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White container with seal" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Seal label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Seals packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Flip-off seal" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Flip-off seal" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass with seal" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White container with seal" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Seal label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Seals packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Flip-off seal" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Flip-off seal" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass with seal" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White container with seal" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Seal label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Seals packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Flip-off seal" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Pharmaceutical" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Flip-off Seals" },
      { label: "Material", value: "Aluminum" },
      { label: "Application", value: "Medical Packaging" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 7,
    name: "RoPP Caps for Pharma PET Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Tamper-proof, reliable RoPP (Roll-on Pilfer Proof) caps that guarantee product safety and consumer confidence. Provides leak-free closure with strong grip and hygienic sealing.",
    images: [
      { src: "/medicine_img/i4.jpg", alt: "RoPP caps and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass with RoPP cap" },
      { src: "/medicine_img/i3.jpg", alt: "White bottle with RoPP cap" },
      { src: "/medicine_img/i4.jpg", alt: "Cap label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Caps packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i1.jpg", alt: "5ml RoPP cap" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass with cap" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White bottle with cap" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Cap label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Caps packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml RoPP cap" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml RoPP cap" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass with cap" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White bottle with cap" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Cap label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Caps packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml RoPP cap" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml RoPP cap" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass with cap" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White bottle with cap" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Cap label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Caps packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml RoPP cap" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml RoPP cap" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass with cap" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White bottle with cap" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Cap label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Caps packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml RoPP cap" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml RoPP cap" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass with cap" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White bottle with cap" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Cap label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Caps packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml RoPP cap" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml RoPP cap" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass with cap" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White bottle with cap" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Cap label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Caps packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml RoPP cap" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml RoPP cap" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass with cap" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White bottle with cap" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Cap label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Caps packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml RoPP cap" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml RoPP cap" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass with cap" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White bottle with cap" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Cap label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Caps packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml RoPP cap" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml RoPP cap" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass with cap" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White bottle with cap" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Cap label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Caps packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml RoPP cap" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Pharmaceutical" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "RoPP Caps" },
      { label: "Material", value: "Plastic" },
      { label: "Application", value: "Bottle Sealing" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 8,
    name: "Toilet cleaner bottles",
    rating: 4.8,
    reviews: 49,
    description: "Specially designed bottles with angled necks for effective and targeted cleaning. Built strong to withstand harsh chemicals and ensure safe handling.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Toilet cleaner bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass toilet cleaner bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White toilet cleaner bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Cleaner label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Cleaner packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i14.jpg", alt: "5ml Toilet cleaner bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White cleaner bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Cleaner label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Cleaner packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Toilet cleaner bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Toilet cleaner bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White cleaner bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Cleaner label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Cleaner packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Toilet cleaner bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Toilet cleaner bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White cleaner bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Cleaner label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Cleaner packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Toilet cleaner bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Toilet cleaner bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White cleaner bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Cleaner label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Cleaner packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Toilet cleaner bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Toilet cleaner bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White cleaner bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Cleaner label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Cleaner packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Toilet cleaner bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Toilet cleaner bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White cleaner bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Cleaner label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Cleaner packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Toilet cleaner bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Toilet cleaner bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White cleaner bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Cleaner label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Cleaner packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Toilet cleaner bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Toilet cleaner bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White cleaner bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Cleaner label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Cleaner packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Toilet cleaner bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Toilet cleaner bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White cleaner bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Cleaner label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Cleaner packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Toilet cleaner bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Household" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Cleaner Bottles" },
      { label: "Material", value: "HDPE" },
      { label: "Application", value: "Cleaning" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 9,
    name: "Cream Jars",
    rating: 4.8,
    reviews: 49,
    description: "Compact, stylish jars suitable for creams, ointments, balms, and gels. Ensures airtight protection, extended shelf life, and premium appeal for skincare and pharma products.",
    images: [
      { src: "/medicine_img/i16.jpg", alt: "Cream jar and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass cream jar" },
      { src: "/medicine_img/i3.jpg", alt: "White cream jar" },
      { src: "/medicine_img/i4.jpg", alt: "Cream jar label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Cream jar packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i10.jpg", alt: "5ml Cream jar" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass cream jar" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White cream jar" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Cream jar label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Cream jar packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Cream jar" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Cream jar" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass cream jar" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White cream jar" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Cream jar label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Cream jar packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Cream jar" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Cream jar" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass cream jar" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White cream jar" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Cream jar label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Cream jar packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Cream jar" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Cream jar" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass cream jar" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White cream jar" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Cream jar label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Cream jar packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Cream jar" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Cream jar" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass cream jar" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White cream jar" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Cream jar label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Cream jar packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Cream jar" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Cream jar" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass cream jar" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White cream jar" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Cream jar label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Cream jar packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Cream jar" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Cream jar" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass cream jar" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White cream jar" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Cream jar label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Cream jar packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Cream jar" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Cream jar" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass cream jar" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White cream jar" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Cream jar label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Cream jar packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Cream jar" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Cream jar" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass cream jar" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White cream jar" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Cream jar label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Cream jar packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Cream jar" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Cosmetic" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Cream Jars" },
      { label: "Material", value: "PP" },
      { label: "Application", value: "Skincare" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 10,
    name: "Shampoo Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Attractive and functional shampoo bottles designed with durability and consumer convenience in mind. Provides smooth dispensing and leak-proof design for personal care brands.",
    images: [
      { src: "/medicine_img/i12.jpg", alt: "Shampoo bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass shampoo bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White shampoo bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Shampoo label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Shampoo packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i1.jpg", alt: "5ml Shampoo bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White shampoo bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Shampoo label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Shampoo packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Shampoo bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Shampoo bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White shampoo bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Shampoo label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Shampoo packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Shampoo bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Shampoo bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White shampoo bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Shampoo label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Shampoo packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Shampoo bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Shampoo bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White shampoo bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Shampoo label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Shampoo packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Shampoo bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Shampoo bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White shampoo bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Shampoo label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Shampoo packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Shampoo bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Shampoo bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White shampoo bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Shampoo label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Shampoo packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Shampoo bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Shampoo bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White shampoo bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Shampoo label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Shampoo packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Shampoo bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Shampoo bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White shampoo bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Shampoo label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Shampoo packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Shampoo bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Shampoo bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass shampoo bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White shampoo bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Shampoo label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Shampoo packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Shampoo bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Personal Care" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Shampoo Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Hair Care" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 11,
    name: "Oil Bottles",
    rating: 4.8,
    reviews: 49,
    description: "Versatile bottles ideal for edible, cosmetic, and therapeutic oils. Engineered for strength, leak resistance, and hygienic preservation of product quality.",
    images: [
      { src: "/medicine_img/i7.jpg", alt: "Oil bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass oil bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White oil bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Oil label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Oil packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i2.jpg", alt: "5ml Oil bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass oil bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White oil bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Oil label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Oil packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Oil bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Oil bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass oil bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White oil bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Oil label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Oil packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Oil bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Oil bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass oil bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White oil bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Oil label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Oil packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Oil bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Oil bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass oil bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White oil bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Oil label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Oil packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Oil bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Oil bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass oil bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White oil bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Oil label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Oil packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Oil bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Oil bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass oil bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White oil bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Oil label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Oil packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Oil bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Oil bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass oil bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White oil bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Oil label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Oil packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Oil bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Oil bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass oil bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White oil bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Oil label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Oil packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Oil bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Oil bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass oil bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White oil bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Oil label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Oil packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Oil bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Food & Cosmetic" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Oil Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Liquid Packaging" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 12,
    name: "Floor cleaner bottles",
    rating: 4.8,
    reviews: 49,
    description: "Ergonomic bottles tailored for strong cleaning solutions. Leak-proof design and comfortable grip make them ideal for safe storage and everyday use.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Floor cleaner bottle and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass floor cleaner bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White floor cleaner bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Cleaner label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Cleaner packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i15.jpg", alt: "5ml Floor cleaner bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White cleaner bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Cleaner label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Cleaner packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Floor cleaner bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Floor cleaner bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White cleaner bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Cleaner label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Cleaner packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Floor cleaner bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Floor cleaner bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White cleaner bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Cleaner label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Cleaner packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Floor cleaner bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Floor cleaner bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White cleaner bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Cleaner label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Cleaner packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Floor cleaner bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Floor cleaner bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White cleaner bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Cleaner label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Cleaner packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Floor cleaner bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Floor cleaner bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White cleaner bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Cleaner label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Cleaner packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Floor cleaner bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Floor cleaner bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White cleaner bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Cleaner label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Cleaner packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Floor cleaner bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Floor cleaner bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White cleaner bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Cleaner label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Cleaner packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Floor cleaner bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Floor cleaner bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass cleaner bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White cleaner bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Cleaner label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Cleaner packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Floor cleaner bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Household" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Cleaner Bottles" },
      { label: "Material", value: "HDPE" },
      { label: "Application", value: "Floor Cleaning" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 13,
    name: "Pharmaceutical rubber Dropper assembly",
    rating: 4.8,
    reviews: 49,
    description: "Precision rubber dropper assemblies for pharmaceutical applications, ensuring accurate dosing and contamination-free delivery for sensitive medical formulations.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Dropper assembly and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass with dropper" },
      { src: "/medicine_img/i3.jpg", alt: "White bottle with dropper" },
      { src: "/medicine_img/i4.jpg", alt: "Dropper label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Dropper packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i6.jpg", alt: "5ml Dropper assembly" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass with dropper" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White bottle with dropper" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Dropper label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Dropper packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Dropper assembly" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Dropper assembly" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass with dropper" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White bottle with dropper" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Dropper label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Dropper packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Dropper assembly" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Dropper assembly" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass with dropper" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White bottle with dropper" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Dropper label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Dropper packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Dropper assembly" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Dropper assembly" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass with dropper" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White bottle with dropper" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Dropper label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Dropper packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Dropper assembly" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Dropper assembly" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass with dropper" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White bottle with dropper" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Dropper label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Dropper packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Dropper assembly" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Dropper assembly" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass with dropper" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White bottle with dropper" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Dropper label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Dropper packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Dropper assembly" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Dropper assembly" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass with dropper" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White bottle with dropper" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Dropper label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Dropper packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Dropper assembly" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Dropper assembly" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass with dropper" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White bottle with dropper" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Dropper label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Dropper packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Dropper assembly" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Dropper assembly" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass with dropper" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White bottle with dropper" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Dropper label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Dropper packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Dropper assembly" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Pharmaceutical" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Dropper Assemblies" },
      { label: "Material", value: "Rubber" },
      { label: "Application", value: "Medical" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 14,
    name: "Stopper CAM Lock fittings for Cold rooms PUF Panels",
    rating: 4.8,
    reviews: 49,
    description: "Heavy-duty lock fittings ensuring airtight and insulated sealing of cold room panels. Provides maximum energy efficiency, durability, and long-term reliability in cold storage.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "CAM lock fittings and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass with CAM lock" },
      { src: "/medicine_img/i3.jpg", alt: "White panel with CAM lock" },
      { src: "/medicine_img/i4.jpg", alt: "Lock label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Lock packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i7.jpg", alt: "5ml CAM lock fittings" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass with lock" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White panel with lock" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Lock label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Lock packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml CAM lock fittings" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml CAM lock fittings" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass with lock" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White panel with lock" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Lock label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Lock packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml CAM lock fittings" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml CAM lock fittings" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass with lock" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White panel with lock" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Lock label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Lock packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml CAM lock fittings" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml CAM lock fittings" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass with lock" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White panel with lock" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Lock label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Lock packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml CAM lock fittings" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml CAM lock fittings" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass with lock" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White panel with lock" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Lock label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Lock packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml CAM lock fittings" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml CAM lock fittings" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass with lock" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White panel with lock" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Lock label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Lock packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml CAM lock fittings" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml CAM lock fittings" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass with lock" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White panel with lock" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Lock label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Lock packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml CAM lock fittings" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml CAM lock fittings" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass with lock" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White panel with lock" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Lock label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Lock packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml CAM lock fittings" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml CAM lock fittings" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass with lock" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White panel with lock" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Lock label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Lock packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml CAM lock fittings" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Industrial" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "CAM Lock Fittings" },
      { label: "Material", value: "Steel" },
      { label: "Application", value: "Cold Storage" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  },
  {
    id: 15,
    name: "Churan Bottle Set",
    rating: 4.8,
    reviews: 49,
    description: "Traditional-style bottles perfect for packaging Ayurvedic churan powders and herbal formulations. Combines cultural appeal with modern packaging standards.",
    images: [
      { src: "/medicine_img/i1.jpg", alt: "Churan bottle set and box mockup" },
      { src: "/medicine_img/i2.jpg", alt: "Brown glass churan bottle" },
      { src: "/medicine_img/i3.jpg", alt: "White churan bottle" },
      { src: "/medicine_img/i4.jpg", alt: "Churan label close-up" },
      { src: "/medicine_img/i5.jpg", alt: "Churan packaging box" },
    ],
    sizeImages: {
      "5 ml": [
        { src: "/medicine_img/i4.jpg", alt: "5ml Churan bottle" },
        { src: "/medicine_img/i2.jpg", alt: "5ml Brown glass churan bottle" },
        { src: "/medicine_img/i3.jpg", alt: "5ml White churan bottle" },
      ],
      "8 ml": [
        { src: "/medicine_img/i4.jpg", alt: "8ml Churan label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "8ml Churan packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "8ml Churan bottle" },
      ],
      "10 ml": [
        { src: "/medicine_img/i7.jpg", alt: "10ml Churan bottle" },
        { src: "/medicine_img/i8.jpg", alt: "10ml Brown glass churan bottle" },
        { src: "/medicine_img/i9.jpg", alt: "10ml White churan bottle" },
      ],
      "15 ml": [
        { src: "/medicine_img/i10.jpg", alt: "15ml Churan label close-up" },
        { src: "/medicine_img/i11.jpg", alt: "15ml Churan packaging box" },
        { src: "/medicine_img/i12.jpg", alt: "15ml Churan bottle" },
      ],
      "20 ml": [
        { src: "/medicine_img/i13.jpg", alt: "20ml Churan bottle" },
        { src: "/medicine_img/i14.jpg", alt: "20ml Brown glass churan bottle" },
        { src: "/medicine_img/i15.jpg", alt: "20ml White churan bottle" },
      ],
      "25 ml": [
        { src: "/medicine_img/i16.jpg", alt: "25ml Churan label close-up" },
        { src: "/medicine_img/i1.jpg", alt: "25ml Churan packaging box" },
        { src: "/medicine_img/i2.jpg", alt: "25ml Churan bottle" },
      ],
      "30 ml": [
        { src: "/medicine_img/i3.jpg", alt: "30ml Churan bottle" },
        { src: "/medicine_img/i4.jpg", alt: "30ml Brown glass churan bottle" },
        { src: "/medicine_img/i5.jpg", alt: "30ml White churan bottle" },
      ],
      "35 ml": [
        { src: "/medicine_img/i6.jpg", alt: "35ml Churan label close-up" },
        { src: "/medicine_img/i7.jpg", alt: "35ml Churan packaging box" },
        { src: "/medicine_img/i8.jpg", alt: "35ml Churan bottle" },
      ],
      "40 ml": [
        { src: "/medicine_img/i9.jpg", alt: "40ml Churan bottle" },
        { src: "/medicine_img/i10.jpg", alt: "40ml Brown glass churan bottle" },
        { src: "/medicine_img/i11.jpg", alt: "40ml White churan bottle" },
      ],
      "45 ml": [
        { src: "/medicine_img/i12.jpg", alt: "45ml Churan label close-up" },
        { src: "/medicine_img/i13.jpg", alt: "45ml Churan packaging box" },
        { src: "/medicine_img/i14.jpg", alt: "45ml Churan bottle" },
      ],
      "50 ml": [
        { src: "/medicine_img/i15.jpg", alt: "50ml Churan bottle" },
        { src: "/medicine_img/i16.jpg", alt: "50ml Brown glass churan bottle" },
        { src: "/medicine_img/i1.jpg", alt: "50ml White churan bottle" },
      ],
      "55 ml": [
        { src: "/medicine_img/i2.jpg", alt: "55ml Churan label close-up" },
        { src: "/medicine_img/i3.jpg", alt: "55ml Churan packaging box" },
        { src: "/medicine_img/i4.jpg", alt: "55ml Churan bottle" },
      ],
      "60 ml": [
        { src: "/medicine_img/i5.jpg", alt: "60ml Churan bottle" },
        { src: "/medicine_img/i6.jpg", alt: "60ml Brown glass churan bottle" },
        { src: "/medicine_img/i7.jpg", alt: "60ml White churan bottle" },
      ],
      "65 ml": [
        { src: "/medicine_img/i8.jpg", alt: "65ml Churan label close-up" },
        { src: "/medicine_img/i9.jpg", alt: "65ml Churan packaging box" },
        { src: "/medicine_img/i10.jpg", alt: "65ml Churan bottle" },
      ],
      "70 ml": [
        { src: "/medicine_img/i11.jpg", alt: "70ml Churan bottle" },
        { src: "/medicine_img/i12.jpg", alt: "70ml Brown glass churan bottle" },
        { src: "/medicine_img/i13.jpg", alt: "70ml White churan bottle" },
      ],
      "75 ml": [
        { src: "/medicine_img/i14.jpg", alt: "75ml Churan label close-up" },
        { src: "/medicine_img/i15.jpg", alt: "75ml Churan packaging box" },
        { src: "/medicine_img/i16.jpg", alt: "75ml Churan bottle" },
      ],
      "80 ml": [
        { src: "/medicine_img/i1.jpg", alt: "80ml Churan bottle" },
        { src: "/medicine_img/i2.jpg", alt: "80ml Brown glass churan bottle" },
        { src: "/medicine_img/i3.jpg", alt: "80ml White churan bottle" },
      ],
      "85 ml": [
        { src: "/medicine_img/i4.jpg", alt: "85ml Churan label close-up" },
        { src: "/medicine_img/i5.jpg", alt: "85ml Churan packaging box" },
        { src: "/medicine_img/i6.jpg", alt: "85ml Churan bottle" },
      ],
    },
    specs: [
      { label: "Color", value: "White" },
      { label: "Usage", value: "Ayurvedic" },
      { label: "Size", value: "Standard" },
      { label: "Product Type", value: "Churan Bottles" },
      { label: "Material", value: "PET" },
      { label: "Application", value: "Herbal Products" },
      { label: "Supply Ability", value: "1000 Per Day" },
      { label: "Delivery Time", value: "4-5 Days" },
    ],
    sizes: [
      "5 ml", "10 ml", "20 ml", "30 ml", "40 ml",
      "50 ml", "60 ml", "70 ml", "80 ml",
      "8 ml", "15 ml", "25 ml", "35 ml", "45 ml",
      "55 ml", "65 ml", "75 ml", "85 ml",
    ],
  }
];

export default products;